title: |`md
  # HFRNet - Containers
`| {
  near: top-center
}
direction: right
container_1: {
  label: "HFR Site\n[Software System]"
  shape: rectangle
  tooltip: "An HFR Station where a SeaSonde/WERA/LERA unit is installed and operating."
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}
container_19: {
  label: "System status website\n[Software System]"
  shape: rectangle
  tooltip: "Services that provides visualizations of products and metrics; manages site configuration."
  style: {
    fill: "#87ceeb"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#5e90a4"
  }
}
container_29: {
  label: "PDA\n[Software System]"
  shape: rectangle
  tooltip: "NESDIS Product Dissemination A???"
  style: {
    fill: "#d3d3d3"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#939393"
  }
}

container_4: {
  label: "HFRNet\n[Software System]"
  shape: rectangle
  tooltip: "Aggregate raw data and process into useful outputs for dissemination."
  style: {
    fill: "#1e2d78"
    font-color: "#ffffff"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#151f54"
  }
}
container_4.container_18: {
  label: "Product Database\n[Container: MySQL]"
  shape: cylinder
  tooltip: "Product database containing site configuration and data flow metrics."
  style: {
    fill: "#87ceeb"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#5e90a4"
  }
}
container_4.container_5: {
  label: "Site Aggregator\n[Container: Python/Shell]"
  shape: rectangle
  tooltip: "Portal(s) to aggregate raw data from sites."
  style: {
    fill: "#87ceeb"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#5e90a4"
  }
}
container_4.container_7: {
  label: "Site Aggregator Database\n[Container: MySQL]"
  shape: cylinder
  tooltip: "Maintain site configuration and [RESEARCH THIS]"
  style: {
    fill: "#87ceeb"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#5e90a4"
  }
}
container_4.container_8: {
  label: "Product Dev\n[Container]"
  shape: rectangle
  tooltip: "Collect data from Site Aggregators and process raw data into products."
  style: {
    fill: "#87ceeb"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#5e90a4"
  }
}
container_4.container_5 -> container_1: {
  label: "Aggregates radials/configuration"
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_4.container_8 -> container_4.container_5: {
  label: "Pulls data from"
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_4.container_8 -> container_4.container_18: {
  label: "Query/update configuration and metrics.\n[TCP/SQL]"
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_4.container_5 -> container_4.container_7: {
  label: "Query/update site configuration."
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_19 -> container_4.container_5: {
  label: "Query/update site configuration."
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_19 -> container_4.container_8: {
  label: "Pull metrics for visualization."
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_4.container_8 -> container_29: {
  label: "Push products to"
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}