title: |`md
  # HFRNet - Deployment - NDBC
`| {
  near: top-center
}
direction: right
container_65: {
  label: "NDBC Dissemination\n[Deployment Node]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#888888"
  }
}
container_65.container_66: {
  label: "Operational Dissemination"
  shape: rectangle
  style: {
    fill: "#d3d3d3"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#939393"
  }
}